#!/bin/bash
TOKEN="eyJhbGciOiJFUzI1NiIsImtpZCI6IjFmYWY5N2IyLTM4NjQtNDQwZi1hNGE1LTQ3MmE2MzI1OTdjMCIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJodHRwczovL2hza2FxdmpydXF6bWdyd3hteHhkLnN1cGFiYXNlLmNvL2F1dGgvdjEiLCJzdWIiOiI3MjFiMTg4Mi1kMTE1LTQyMjAtYTEwMS1lNjViZDRiMzlmNjkiLCJhdWQiOiJhdXRoZW50aWNhdGVkIiwiZXhwIjoxNzY4OTUwNjM2LCJpYXQiOjE3Njg5NDcwMzYsImVtYWlsIjoianVuYWlkQGV4YW1wbGUuY29tIiwicGhvbmUiOiIiLCJhcHBfbWV0YWRhdGEiOnsicHJvdmlkZXIiOiJlbWFpbCIsInByb3ZpZGVycyI6WyJlbWFpbCJdfSwidXNlcl9tZXRhZGF0YSI6eyJlbWFpbCI6Imp1bmFpZEBleGFtcGxlLmNvbSIsImVtYWlsX3ZlcmlmaWVkIjp0cnVlLCJwaG9uZV92ZXJpZmllZCI6ZmFsc2UsInN1YiI6IjcyMWIxODgyLWQxMTUtNDIyMC1hMTAxLWU2NWJkNGIzOWY2OSJ9LCJyb2xlIjoiYXV0aGVudGljYXRlZCIsImFhbCI6ImFhbDEiLCJhbXIiOlt7Im1ldGhvZCI6InBhc3N3b3JkIiwidGltZXN0YW1wIjoxNzY4OTQ3MDM2fV0sInNlc3Npb25faWQiOiJhYjUzZDRhMC05NDRkLTRkMmItOTg3ZC0xN2Y4MDkzMjYwZGQiLCJpc19hbm9ueW1vdXMiOmZhbHNlfQ.zSGkKDQnsDNqa8hNSzF4llmuwlvBGaGCLJ83zA4wn7vtMhYJvFm0iMjKpOVx9zncW5n6-nZ-oZArJl7AJAQZdA"

echo "Testing Same Password (Expect 400)..."
curl -s -v -X POST 'https://hskaqvjruqzmgrwxmxxd.supabase.co/functions/v1/resetPassword' \
  -H 'apikey: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZS1kZW1vIiwicm9sZSI6ImFub24iLCJleHAiOjE5ODM4MTI5OTZ9.CRXP1A7WOeoJeXxjNni43kdQwgnWNReilDMblYTn_I0' \
  -H 'Content-Type: application/json' \
  -d "{\"access_token\": \"$TOKEN\", \"newPassword\": \"SecurePass123!\"}"
echo ""
echo "Done."
